### ISSUE TITLE
Passbolt app 1.3 crashes on /e/ on scanning QR Code

### ISSUE THREAD

**Issue by ldubost** [passbolt/mobile-passbolt-android#1]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to an installation: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt Android Mobile App.
For passbolt API, docker, command line interface, in short any other bugs
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new Android bug please use the following format:

## ISSUE NAME
* Passbolt Version: 1.3.0
* Platform and Target:
  -- Passbolt Android App: 1.3.0
  -- Android OS: /e/
  -- Phone: Murena Fairephone 4
  -- Passbolt API: not relevant
  -- Device language: FR,
   
### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

1. Manual install of apk from https://apkplz.net/app/com.passbolt.mobile.android
2. Open passbolt app (app complains device maybe rooted -> which I believe is untrue)
3. Click on "Connect to existing account"
4. Click on "Scan QR Codes"
5. Authorize screen shows up, click on one of the Allows (one time or when app in use)
6. Passbolt crashes and disappears. No message about the crash

On retries if authorization already given it crashes on scan qr codes directly.

### What happened

Passbolt crashed

### What you expected to happen

Passbolt would not crash and camera shows up to scan QR Code

**Comment by ldubost** [comment]
Hi @stripthis,

Thanks for getting back.

I perfectly understand that given the newness of the app (which is a great progress btw - at XWiki passbolt is very important tool and having access to the passwords on mobile is very important), you can't test on all systems.

Is it an Android OS crash report that you need ?  I saw a menu in Passbolt with logs but it seemed to be empty.
I'm not super familiar with crash reports and if they contain the application crash information. I'd like to confirm this in order to avoid sending you useless data.

For apkplz.net, it's a good point. I asked /e/ to add your package (they have some mirroring of Google Play as far as I know) but it's not available yet. So I used this source for manual install as a workaround. It's clearly not legit in the sense that it's probably hard to control what's there. F-Droid is a very good idea IMHO and would be helpful for /e/ (though I'm new to /e/ so I could be wrong)

For the rooted warning I did check without the setting you mention (I had it initially). The warning is still there. It could be interesting to have a setting to ignore it as it could be annoying if you know what to do. I see why it could be a bad idea in most cases however as if your Phone gets rooted without your knowledge (if that's possible) it might be interesting to get a warning.

**Comment by AnatomicJC** [comment]
Hi @ldubost,

From Setting menu of our Android app, you can enable debug logs, which is disabled by default. Once enabled, reproduce your issue then send us the logs. You can share them by clicking on the share icon on the top right.

Best,

![image](https://user-images.githubusercontent.com/2129821/153418166-2e6e9f89-be27-420e-a650-2b3f25df65da.png)

**Comment by ldubost** [comment]
I'm up to it. I thought about building it ! Thanks for the pointer. I'll see if I can try this this week-end. However the link you gave seems to be private.

You must mean the dark side of Passbolt, as I believe I know the dark side of Open Source: https://cryptpad.fr/ !

**Comment by nourcy** [comment]
Oops pardon..

# How to build locally

## With Android Studio (recommended)
1. Launch [Android Studio](https://developer.android.com/studio) and open the cloned project
2. Make sure that Android SDK with version `30` is installed to compile the project
3. Wait until project configuration finishes (couple of minutes) and click `Sync with Gradle files` icon (top right toolbar - elephant with blue arrow) 
4. Open the `Build Variants` tab (bottom left vertical pane) and under the `:app` module select `Active Build Variant` as `debug`
5. Prepare a device for launch - at minimum `Android 10 (API 30)` is required
   1. [create and launch Android emulator](https://developer.android.com/studio/run/managing-avds) **or**
   2. [set up and launch on a real device](https://developer.android.com/studio/run/device)
6. Hit the `Run` arrow (green play icon in the top center)

**Comment by marcin-michalek-miquido** [comment]
Hello, thank you for verifying that local build works fine. The code from `master (13b62334)` is exactly the one used to build the `1.3.0` version available on the Play Store. That creates one more possible cause - the packaging. For the Play Store we use the [App Bundle](https://developer.android.com/guide/app-bundle) format - we build the `.aab` file from which the Play Store generates multiple `.apk` which have smaller size (they contain only per-device content in regards of CPU architecture for native libraries (such as one used during QR scanning), image assets, etc). I see that apkplz.net have their own installer which should be able to assemble the full `.apk` from splits, but it's possible that something went wrong there.
We have created a task for publishing to F-Droid and we will investigate it and complete in the next sprint (starting from 21/02). Once published we will notify you here. We will also verify the installation from F-Droid on our Lineage OS device.

P.S the debug logo is because of the debug build variant chosen (point 4 above) - the logo(icon) makes it easier to distinguish between installed variants - to not confuse it with production version if both are installed on the device.

**Comment by githnu** [comment]
I just downloaded Passbolt 1.9.0 from the play store and installed it in lineageos 18.1. I am experiencing this exact same bug after clicking scan QR codes. The camera flashes ever so briefly for one or so frames and then app crashes. It does not appear that there is any alternative installation method when this doesn't work.

Note I also do not have google play services installed since I am deliberately avoiding google.

On another older android phone the exact same APK works though.

You mentioned submitting to fdroid, yes please do! It gets very frustrating when software publishers will not publish their APKs for android forks.

**Comment by marcin-michalek-miquido** [comment]
hello @githnu, 
would it be possible for you to turn on the logs and check if there are crash details there?

1. launch the app on the "Welcome" screen
2. click the "?" icon in the top right corner
3. toggle the "Enable debug logs" switch
4. go to the scanning qr codes where the app crashes
5. releaunch the app on the "Welcome" screen and go to the "?" icon again
6. click "Access the logs"

I am not sure if for this particular crash there will be sth there, but if it is, the content would help us to diagnose the possible issue.
It may be releated to installation as @ldubost had a simiallr issue and the app built by himself from Android Studio worked well. Right now I checked the app on LineageOS 18.1 on an old Samsung Galaxy S4 and the app works fine there (install from Android Studio) - I can also try instalilng the app the same way you did to see if I can reproduce ther issue, if you could share the details on how you did the installation.

**Comment by githnu** [comment]
Here's the debug log, apparently an object file is missing. BTW it shows the error twice and is not a copy mistake.
I tried installing it different ways, but this copy was transfered from a working phone using sharik to install the APK. What way should I try to install it?

> Device: OnePlus KB2003
> Android 11 (30)
> Passbolt 1.9.0-11
> 
> 
> 02:51:11 Uncaught exception in thread: pool-3-thread-2
> java.lang.UnsatisfiedLinkError: dlopen failed: library "libbarhopper_v3.so" not found
> at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
> at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
> at java.lang.System.loadLibrary(System.java:1664)
> at com.google.android.libraries.barhopper.BarhopperV3.<init>(SourceFile:1)
> at com.google.mlkit.vision.barcode.bundled.internal.zza.zzc(SourceFile:1)
> at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(SourceFile:8)
> at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(SourceFile:3)
> at android.os.Binder.transact(Binder.java:1043)
> at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzc(SourceFile:2)
> at com.google.android.gms.internal.mlkit_vision_barcode.zzox.zze(SourceFile:2)
> at com.google.mlkit.vision.barcode.internal.zzl.zza(SourceFile:3)
> at com.google.mlkit.vision.barcode.internal.zzi.zzc(SourceFile:3)
> at com.google.mlkit.vision.barcode.internal.zzi.run(SourceFile:1)
> at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(SourceFile:2)
> at com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
> at com.google.mlkit.common.sdkinternal.ModelResource.zza(SourceFile:8)
> at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
> at com.google.mlkit.common.sdkinternal.zzp.run(SourceFile:2)
> at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(SourceFile:4)
> at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(SourceFile:1)
> at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(SourceFile:2)
> at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
> at java.lang.Thread.run(Thread.java:923)
> 
> java.lang.UnsatisfiedLinkError: dlopen failed: library "libbarhopper_v3.so" not found
> at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
> at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
> at java.lang.System.loadLibrary(System.java:1664)
> at com.google.android.libraries.barhopper.BarhopperV3.<init>(SourceFile:1)
> at com.google.mlkit.vision.barcode.bundled.internal.zza.zzc(SourceFile:1)
> at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(SourceFile:8)
> at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(SourceFile:3)
> at android.os.Binder.transact(Binder.java:1043)
> at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzc(SourceFile:2)
> at com.google.android.gms.internal.mlkit_vision_barcode.zzox.zze(SourceFile:2)
> at com.google.mlkit.vision.barcode.internal.zzl.zza(SourceFile:3)
> at com.google.mlkit.vision.barcode.internal.zzi.zzc(SourceFile:3)
> at com.google.mlkit.vision.barcode.internal.zzi.run(SourceFile:1)
> at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(SourceFile:2)
> at com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
> at com.google.mlkit.common.sdkinternal.ModelResource.zza(SourceFile:8)
> at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
> at com.google.mlkit.common.sdkinternal.zzp.run(SourceFile:2)
> at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(SourceFile:4)
> at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(SourceFile:1)
> at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(SourceFile:2)
> at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
> at java.lang.Thread.run(Thread.java:923)
> 02:51:16 File logging tree planted

**Comment by githnu** [comment]
I was not able to find any prebuilt APKs that work on a virgin lineageos install. Maybe a future version might make the QR code optional?

Regarding alternatives not being a priority, I get it, the overwhelming majority of businesses and app developers also share that view and they don't understand/care why I use alternatives. I try to vote with my feet to support alternatives instead of the apple/google duopoly, but it's been so difficult. Not picking on you in particular, it's a battle with nearly every mobile app to provide any official support. I just feel defeated.

I do appreciate your responding and help though.

**Comment by stripthis** [comment]
@githnu I feel you, we also want to support people who are going to alternatives as it is in line with our value. We'll offer F-Droid support, most likely in 2023. Thank you for your patience.

**Comment by AnatomicJC** [comment]
@githnu if you are interested by installing apps from Google Play Store without any Google account, you can give a try to Aurora store, available on F-droid. Aurora acts as a proxy between you and the Play store.
It can be an alternative.
You can install from my f-droid repo previous versions from the passbolt apk but I guess you will have the same bug. Using latest version is highly recommended as it contains usually security fixes.

Best,

**Comment by githnu** [comment]
Good news: the Aurora store was able to install Passbolt 1.9.0-11 and the QR code reader works this time! BTW to anyone else encountering this: it was necessary for me to uninstall the previous APK of the exact same version number, otherwise the install "succeeds" without updating the actual files.

I remember google had broken the anonymous clients including aurora on 9 pie, so it's good to see that anonymous connections from aurora store are working now.

@AnatomicJC @stripthis, thank you both for the helpful suggestions.
