### ISSUE TITLE
App Crashes After Login (DateTimeParseException)

### ISSUE THREAD

**Issue by tldawson** [passbolt/mobile-passbolt-android#4]
## App Crashes After Login (DateTimeParseException)
* Passbolt Version: 3.8.3
* Platform and Target: 
  -- Passbolt Android App: 1.11.0
  -- Android OS: LineageOS 19-20221117-NIGHTLY-barbet (Android 12)
  -- Phone: Google Pixel 5a
  -- Passbolt API: 3.8.3
  -- Device language: en-US

### What you did

1. Install Passbolt mobile from the Play Store
2. Connect existing account by scanning QR codes in desktop browser
3. Enter passphrase on mobile app

### What happened

After the passphrase is submitted, the app crashes. The logs seem to indicate its an issue with parsing the datetime string:
[passbolt-mobile.log](https://github.com/passbolt/mobile-passbolt-android/files/10483053/passbolt-mobile.log)

### What you expected to happen

The app to show my list of passwords like on desktop.

**Comment by marcin-michalek-miquido** [comment]
hello @tldawson, you are correct the issue is with the date time parsing. 
On your server the date time field has value of `2021-10-22T19:34:41` and we use [ZonedDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#parse-java.lang.CharSequence-) to parse the date times (so we expect format of `2021-10-22T19:34:41+00:00` or `2021-10-22T19:34:41Z`). 
I will see with the backend / support team if this can be achieved by configuring the server or we need to handle it some other way. BTW time looks out of sync - the correct time will need to be set and synced on the server for the mobile authentication to work.

**Comment by claytontstevenson** [comment]
hey @tldawson could you let me know what OS your server is and if you installed via source or the package? With that I'll be better able to point you in the correct direction

**Comment by tldawson** [comment]
@claytontstevenson The server was running Amazon Linux and Passbolt was installed from source.  
Ultimately, I migrated to the prebuilt AMI because my users needed access to the mobile app feature... but the mobile app would still benefit from the flexibility of supporting less rigid datetime formats. I still have backups of the previous AMI, if you have any questions about the configuration.

**Comment by pabloelcolombiano** [comment]
@tldawson I have add a post on the community forum, where I propose to continue the discussion.  Feel free to provide us with additional info, as suggested in this [post](https://community.passbolt.com/t/android-app-1-13-2-crashes-with-no-error/7479/9).

**Comment by luisogandob** [comment]
Hi, same behavior here, but I'm using the docker version of Passbolt.

**Comment by marcin-michalek-miquido** [comment]
Hello guys - an additional date format enforcement [was added to the API](https://community.passbolt.com/t/android-app-1-13-2-crashes-with-no-error/7479/15?u=mmichalek) (v.4.1) in [this commit](https://github.com/passbolt/passbolt_api/commit/c823afc6af14e3e53741963f674a5cd10cfddadc). This should fix the issue.
